### ISSUE TITLE
Cleanup Tasks

### ISSUE THREAD

**Issue by jdorfman** [stackshareio/awesome-stacks#12]
- [x] Keep or remove `Contents` section? (See #11) 
- [x] Rename `serverless-stack.com ↗` to `Serverless ↗`
- [x] Remove `React Native for the F8 App ↗`? via @yonasb 
- [x] Add Good vs Bad stack examples to `CONTRIBUTING.md`
- [x] Fix url `https://awesomestacks.dev/victor-hugo` > `victor-hugo-boilerplate`
- [x] Title Case
- [x] Remove "stack" from `Ethereum DApp stack ↗`
- [x] hugo-algolia link fix
- [x] On ProductHunt button

**Comment by dzello** [comment]
For serverless-stack.com to Serverless, that was a change from user feedback. The complaint was that there's not just one serverless stack and the tools in this one are AWS-centric, which is just one way to do it. So that didn't sit well, just using "Serverless" as the title.
