### ISSUE TITLE
Fix Twitter OG Image

### ISSUE THREAD

**Issue by jdorfman** [stackshareio/awesome-stacks#18]
![image](https://user-images.githubusercontent.com/398230/55857255-723a9100-5b21-11e9-9399-ef6222daa372.png)

via https://cards-dev.twitter.com/validator

**Comment by dzello** [comment]
Looking at this now

**Comment by dzello** [comment]
Should be good now. After trying a few things it looks like it was the image size. I shrunk it from 1.7MB to about 600KB and then it finally took it. cc @patrickjwoods 

![Screenshot 2019-04-10 09 41 00](https://user-images.githubusercontent.com/174777/55860545-c458d200-5b74-11e9-8842-fb9e945b520c.png)
