### ISSUE TITLE
Serverless stack is too specific/ opinionated

### ISSUE THREAD

**Issue by rezanid** [stackshareio/awesome-stacks#19]
I think the Serverless stack is too opinionated / specific. It’s mostly promoting AWS. The Serverless framework (which is awesome by the way) is only supporting JavaScript. I suggest changing the name of this stack to AWS Serverless. There can be other stacks for Google, Azure, and others.

**Comment by jdorfman** [comment]
@rezanid this is **_excellent feedback_**! Once I catch some zzz's I will look into possibly renaming it to AWS Serverless. 

In the meantime, would you like to make a PR for Azure and/or GCP Serverless? No pressure, I was thinking of creating `First Timers Only` issues for those just learning to code.

**Comment by rezanid** [comment]
I have some ideas for a first timer Azure Serverless. I will have to check your template first ;)

**Comment by AlexSwensen** [comment]
Similarly, Angular is an awesome framework but is not included while React and Vue both are.

**Comment by dzello** [comment]
This stack is based on the tools described at [serverless-stack.com](https://serverless-stack.com/) which admittedly has a very generic name. I can see why it caused confusion. I will change it's name. Thanks for pointing this out. Feel free to add other serverless stack examples with different tools, the more the merrier.
