### ISSUE TITLE
Vue with three.js

### ISSUE THREAD

**Issue by uditgogoi** [stackshareio/awesome-stacks#45]
Is it possible to contribute Vue with three.js library ?

**Comment by jdorfman** [comment]
Hi, can you give me a little more context?

**Comment by uditgogoi** [comment]
Is it possible to include development of 3D scenes using three.js with vue

**Comment by jdorfman** [comment]
@uditgogoi sounds interesting. If you want to create a PR go for it.

**Comment by uditgogoi** [comment]
Ok thanks the reply. I will try to contribute towards it

**Comment by jdorfman** [comment]
Looking forward to it =)
