### ISSUE TITLE
MEAN stack

### ISSUE THREAD

**Issue by harikesh409** [stackshareio/awesome-stacks#56]
There is no stack for MEAN. You can add [mean](https://github.com/meanjs/mean).

**Comment by jdorfman** [comment]
Hi @harikesh409 we are looking for more specific stacks e.g. "MEAN + X for doing Y". We already have [MEAN](https://stackshare.io/mean) so it doesn't make sense to add it here.

Thanks!

P.S. more info here: https://github.com/stackshareio/awesome-stacks/blob/master/CONTRIBUTING.md#contributing-dos-and-donts
