### ISSUE TITLE
Why MEAN stack is not listed?

### ISSUE THREAD

**Issue by program-om** [stackshareio/awesome-stacks#62]
I am wondering why MEAN (MongoDB, ExpressJS, Angular, and NodeJS) stack is not listed? is it not popular enough? or what is the reason?

**Comment by jdorfman** [comment]
Hi @program-om,

Great question. Since [MEAN](https://stackshare.io/mean) is already on StackShare we, we didn't think to add it. You are more than welcome to open a PR.

> ✅ Do submit stacks that represent a reusable pattern or architecture like LAMP or MEVN

More guidelines: https://github.com/stackshareio/awesome-stacks/blob/master/CONTRIBUTING.md

**Comment by jdorfman** [comment]
Closing for now
